//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8936
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1_8ZsXWqdo9OwAfwychr3zEw3 {
            get {
                object obj = ResourceManager.GetObject("1_8ZsXWqdo9OwAfwychr3zEw3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _121_Healthy_Snacks_For_Every_Type_of_Snacker {
            get {
                object obj = ResourceManager.GetObject("121-Healthy-Snacks-For-Every-Type-of-Snacker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _15070_alhallabrestaurantandsweets_1_Hero_Desktop {
            get {
                object obj = ResourceManager.GetObject("15070_alhallabrestaurantandsweets_1_Hero_Desktop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _15070_alhallabrestaurantandsweets_1_Hero_Desktop__1_ {
            get {
                object obj = ResourceManager.GetObject("15070_alhallabrestaurantandsweets_1_Hero_Desktop (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _36390468_portrait_of_male_manager_using_digital_tablet_in_warehouse {
            get {
                object obj = ResourceManager.GetObject("36390468-portrait-of-male-manager-using-digital-tablet-in-warehouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _38540811_324042098167104_3998971013386731520_n {
            get {
                object obj = ResourceManager.GetObject("38540811_324042098167104_3998971013386731520_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _40399237_862784877444496_1248152781851122799_n {
            get {
                object obj = ResourceManager.GetObject("40399237_862784877444496_1248152781851122799_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _40740722_1096768193816976_3243845275913295963_n {
            get {
                object obj = ResourceManager.GetObject("40740722_1096768193816976_3243845275913295963_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _40740722_1096768193816976_3243845275913295963_n1 {
            get {
                object obj = ResourceManager.GetObject("40740722_1096768193816976_3243845275913295963_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap a48b9331608413_5675f59abec9d {
            get {
                object obj = ResourceManager.GetObject("a48b9331608413.5675f59abec9d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arvato_warehouse_adaptive_768__2_ {
            get {
                object obj = ResourceManager.GetObject("arvato_warehouse.adaptive.768 (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Beverage_Milk_01 {
            get {
                object obj = ResourceManager.GetObject("Beverage-Milk-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Beverage_Milk_011 {
            get {
                object obj = ResourceManager.GetObject("Beverage-Milk-011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Beverage_Milk_02 {
            get {
                object obj = ResourceManager.GetObject("Beverage-Milk-02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Chart_Printing {
            get {
                object obj = ResourceManager.GetObject("Chart-Printing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Chart_Printing1 {
            get {
                object obj = ResourceManager.GetObject("Chart-Printing1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Chart_Printing2 {
            get {
                object obj = ResourceManager.GetObject("Chart-Printing2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Chart_Printing3 {
            get {
                object obj = ResourceManager.GetObject("Chart-Printing3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Clean {
            get {
                object obj = ResourceManager.GetObject("Clean", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Clean_brush_ {
            get {
                object obj = ResourceManager.GetObject("Clean brush ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Clean_brush_1 {
            get {
                object obj = ResourceManager.GetObject("Clean brush 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Clean_brush_2 {
            get {
                object obj = ResourceManager.GetObject("Clean brush 2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Clean_WF {
            get {
                object obj = ResourceManager.GetObject("Clean-WF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Clear {
            get {
                object obj = ResourceManager.GetObject("Clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cross_Close {
            get {
                object obj = ResourceManager.GetObject("Cross Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cyan_mountains_by_ciandesign_d7zocc21 {
            get {
                object obj = ResourceManager.GetObject("cyan_mountains_by_ciandesign-d7zocc21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dsce {
            get {
                object obj = ResourceManager.GetObject("dsce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ecommerce {
            get {
                object obj = ResourceManager.GetObject("ecommerce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ecommerce1 {
            get {
                object obj = ResourceManager.GetObject("ecommerce1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fruit_Apple_WF {
            get {
                object obj = ResourceManager.GetObject("Fruit Apple-WF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fruit_Apple_WF1 {
            get {
                object obj = ResourceManager.GetObject("Fruit Apple-WF1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fruit_Apple_WF2 {
            get {
                object obj = ResourceManager.GetObject("Fruit Apple-WF2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GimbalBarcode_High_Res {
            get {
                object obj = ResourceManager.GetObject("GimbalBarcode_High-Res", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap if_icon_minus_round_211863 {
            get {
                object obj = ResourceManager.GetObject("if_icon-minus-round_211863", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Impuesto_Renta {
            get {
                object obj = ResourceManager.GetObject("Impuesto-Renta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kisspng_computer_icons_symbol_plus_and_minus_signs_minus_5b1a0cf4f26108_0029977115284339089928 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-symbol-plus-and-minus-signs-minus-5b1a0cf4f26108.002997711" +
                        "5284339089928", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kisspng_computer_icons_symbol_plus_and_minus_signs_minus_5b1a0cf4f261081 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-symbol-plus-and-minus-signs-minus-5b1a0cf4f261081", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap manajemen_persediaan {
            get {
                object obj = ResourceManager.GetObject("manajemen-persediaan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap maxresdefault1 {
            get {
                object obj = ResourceManager.GetObject("maxresdefault1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Milk_Bottle {
            get {
                object obj = ResourceManager.GetObject("Milk-Bottle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Milk_Bottle1 {
            get {
                object obj = ResourceManager.GetObject("Milk-Bottle1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Milk_Bottle2 {
            get {
                object obj = ResourceManager.GetObject("Milk-Bottle2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Milk_Bottle3 {
            get {
                object obj = ResourceManager.GetObject("Milk-Bottle3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap new_logo {
            get {
                object obj = ResourceManager.GetObject("new_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap No_01 {
            get {
                object obj = ResourceManager.GetObject("No-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap No_011 {
            get {
                object obj = ResourceManager.GetObject("No-011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap photo_1522308300961_fdb949cac8aa {
            get {
                object obj = ResourceManager.GetObject("photo-1522308300961-fdb949cac8aa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pizza_01 {
            get {
                object obj = ResourceManager.GetObject("Pizza-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pizza_011 {
            get {
                object obj = ResourceManager.GetObject("Pizza-011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pizza_012 {
            get {
                object obj = ResourceManager.GetObject("Pizza-012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pizza_02 {
            get {
                object obj = ResourceManager.GetObject("Pizza-02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pizza_021 {
            get {
                object obj = ResourceManager.GetObject("Pizza-021", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap plus_big_512 {
            get {
                object obj = ResourceManager.GetObject("plus-big-512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap postanti_as_barcodemain {
            get {
                object obj = ResourceManager.GetObject("postanti.as_barcodemain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap postanti_as_barcodemain__2_ {
            get {
                object obj = ResourceManager.GetObject("postanti.as_barcodemain (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap postanti_as_barcodemain__3_ {
            get {
                object obj = ResourceManager.GetObject("postanti.as_barcodemain (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap postanti1 {
            get {
                object obj = ResourceManager.GetObject("postanti1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Settings_01 {
            get {
                object obj = ResourceManager.GetObject("Settings-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Settings_011 {
            get {
                object obj = ResourceManager.GetObject("Settings-011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Settings1 {
            get {
                object obj = ResourceManager.GetObject("Settings1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Settings2 {
            get {
                object obj = ResourceManager.GetObject("Settings2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Settings3 {
            get {
                object obj = ResourceManager.GetObject("Settings3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Settings4 {
            get {
                object obj = ResourceManager.GetObject("Settings4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Settings5 {
            get {
                object obj = ResourceManager.GetObject("Settings5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Settings6 {
            get {
                object obj = ResourceManager.GetObject("Settings6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap startupstockphotos {
            get {
                object obj = ResourceManager.GetObject("startupstockphotos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Strawberry1 {
            get {
                object obj = ResourceManager.GetObject("Strawberry1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Strawberry11 {
            get {
                object obj = ResourceManager.GetObject("Strawberry11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Strawberry12 {
            get {
                object obj = ResourceManager.GetObject("Strawberry12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
