//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8937
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace FSM.Reports {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("Production")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class Production : global::System.Data.DataSet {
        
        private Production_tableDataTable tableProduction_table;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Production() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected Production(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["Production_table"] != null)) {
                    base.Tables.Add(new Production_tableDataTable(ds.Tables["Production_table"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public Production_tableDataTable Production_table {
            get {
                return this.tableProduction_table;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            Production cln = ((Production)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["Production_table"] != null)) {
                    base.Tables.Add(new Production_tableDataTable(ds.Tables["Production_table"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableProduction_table = ((Production_tableDataTable)(base.Tables["Production_table"]));
            if ((initTable == true)) {
                if ((this.tableProduction_table != null)) {
                    this.tableProduction_table.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "Production";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/Production.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableProduction_table = new Production_tableDataTable();
            base.Tables.Add(this.tableProduction_table);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeProduction_table() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            Production ds = new Production();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void Production_tableRowChangeEventHandler(object sender, Production_tableRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class Production_tableDataTable : global::System.Data.TypedTableBase<Production_tableRow> {
            
            private global::System.Data.DataColumn columnproduct_dep;
            
            private global::System.Data.DataColumn columnproduct;
            
            private global::System.Data.DataColumn columndate;
            
            private global::System.Data.DataColumn columntime;
            
            private global::System.Data.DataColumn columnto_date;
            
            private global::System.Data.DataColumn columnfrom_date;
            
            private global::System.Data.DataColumn columnbatch_no;
            
            private global::System.Data.DataColumn columnitem;
            
            private global::System.Data.DataColumn columnqty;
            
            private global::System.Data.DataColumn columnstatus;
            
            private global::System.Data.DataColumn columnqty1;
            
            private global::System.Data.DataColumn columnqty2;
            
            private global::System.Data.DataColumn columnqty3;
            
            private global::System.Data.DataColumn columnqty4;
            
            private global::System.Data.DataColumn columnqty5;
            
            private global::System.Data.DataColumn columnqty6;
            
            private global::System.Data.DataColumn columnqty7;
            
            private global::System.Data.DataColumn columnqty8;
            
            private global::System.Data.DataColumn columnqty9;
            
            private global::System.Data.DataColumn columnqty10;
            
            private global::System.Data.DataColumn columnqty11;
            
            private global::System.Data.DataColumn columnqty12;
            
            private global::System.Data.DataColumn columnqty13;
            
            private global::System.Data.DataColumn columnqty14;
            
            private global::System.Data.DataColumn columnqty15;
            
            private global::System.Data.DataColumn columnqty16;
            
            private global::System.Data.DataColumn columnqty17;
            
            private global::System.Data.DataColumn columnqty18;
            
            private global::System.Data.DataColumn columnqty19;
            
            private global::System.Data.DataColumn columnqty20;
            
            private global::System.Data.DataColumn columnqty21;
            
            private global::System.Data.DataColumn columnqty22;
            
            private global::System.Data.DataColumn columnbranch;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Production_tableDataTable() {
                this.TableName = "Production_table";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal Production_tableDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected Production_tableDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn product_depColumn {
                get {
                    return this.columnproduct_dep;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn productColumn {
                get {
                    return this.columnproduct;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn dateColumn {
                get {
                    return this.columndate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn timeColumn {
                get {
                    return this.columntime;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn to_dateColumn {
                get {
                    return this.columnto_date;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn from_dateColumn {
                get {
                    return this.columnfrom_date;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn batch_noColumn {
                get {
                    return this.columnbatch_no;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn itemColumn {
                get {
                    return this.columnitem;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn qtyColumn {
                get {
                    return this.columnqty;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn statusColumn {
                get {
                    return this.columnstatus;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn qty1Column {
                get {
                    return this.columnqty1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn qty2Column {
                get {
                    return this.columnqty2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn qty3Column {
                get {
                    return this.columnqty3;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn qty4Column {
                get {
                    return this.columnqty4;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn qty5Column {
                get {
                    return this.columnqty5;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn qty6Column {
                get {
                    return this.columnqty6;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn qty7Column {
                get {
                    return this.columnqty7;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn qty8Column {
                get {
                    return this.columnqty8;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn qty9Column {
                get {
                    return this.columnqty9;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn qty10Column {
                get {
                    return this.columnqty10;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn qty11Column {
                get {
                    return this.columnqty11;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn qty12Column {
                get {
                    return this.columnqty12;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn qty13Column {
                get {
                    return this.columnqty13;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn qty14Column {
                get {
                    return this.columnqty14;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn qty15Column {
                get {
                    return this.columnqty15;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn qty16Column {
                get {
                    return this.columnqty16;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn qty17Column {
                get {
                    return this.columnqty17;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn qty18Column {
                get {
                    return this.columnqty18;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn qty19Column {
                get {
                    return this.columnqty19;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn qty20Column {
                get {
                    return this.columnqty20;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn qty21Column {
                get {
                    return this.columnqty21;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn qty22Column {
                get {
                    return this.columnqty22;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn branchColumn {
                get {
                    return this.columnbranch;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Production_tableRow this[int index] {
                get {
                    return ((Production_tableRow)(this.Rows[index]));
                }
            }
            
            public event Production_tableRowChangeEventHandler Production_tableRowChanging;
            
            public event Production_tableRowChangeEventHandler Production_tableRowChanged;
            
            public event Production_tableRowChangeEventHandler Production_tableRowDeleting;
            
            public event Production_tableRowChangeEventHandler Production_tableRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddProduction_tableRow(Production_tableRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Production_tableRow AddProduction_tableRow(
                        string product_dep, 
                        string product, 
                        string date, 
                        string time, 
                        string to_date, 
                        string from_date, 
                        string batch_no, 
                        string item, 
                        string qty, 
                        string status, 
                        string qty1, 
                        string qty2, 
                        string qty3, 
                        string qty4, 
                        string qty5, 
                        string qty6, 
                        string qty7, 
                        string qty8, 
                        string qty9, 
                        string qty10, 
                        string qty11, 
                        string qty12, 
                        string qty13, 
                        string qty14, 
                        string qty15, 
                        string qty16, 
                        string qty17, 
                        string qty18, 
                        string qty19, 
                        string qty20, 
                        string qty21, 
                        string qty22, 
                        string branch) {
                Production_tableRow rowProduction_tableRow = ((Production_tableRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        product_dep,
                        product,
                        date,
                        time,
                        to_date,
                        from_date,
                        batch_no,
                        item,
                        qty,
                        status,
                        qty1,
                        qty2,
                        qty3,
                        qty4,
                        qty5,
                        qty6,
                        qty7,
                        qty8,
                        qty9,
                        qty10,
                        qty11,
                        qty12,
                        qty13,
                        qty14,
                        qty15,
                        qty16,
                        qty17,
                        qty18,
                        qty19,
                        qty20,
                        qty21,
                        qty22,
                        branch};
                rowProduction_tableRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowProduction_tableRow);
                return rowProduction_tableRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                Production_tableDataTable cln = ((Production_tableDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new Production_tableDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnproduct_dep = base.Columns["product_dep"];
                this.columnproduct = base.Columns["product"];
                this.columndate = base.Columns["date"];
                this.columntime = base.Columns["time"];
                this.columnto_date = base.Columns["to_date"];
                this.columnfrom_date = base.Columns["from_date"];
                this.columnbatch_no = base.Columns["batch_no"];
                this.columnitem = base.Columns["item"];
                this.columnqty = base.Columns["qty"];
                this.columnstatus = base.Columns["status"];
                this.columnqty1 = base.Columns["qty1"];
                this.columnqty2 = base.Columns["qty2"];
                this.columnqty3 = base.Columns["qty3"];
                this.columnqty4 = base.Columns["qty4"];
                this.columnqty5 = base.Columns["qty5"];
                this.columnqty6 = base.Columns["qty6"];
                this.columnqty7 = base.Columns["qty7"];
                this.columnqty8 = base.Columns["qty8"];
                this.columnqty9 = base.Columns["qty9"];
                this.columnqty10 = base.Columns["qty10"];
                this.columnqty11 = base.Columns["qty11"];
                this.columnqty12 = base.Columns["qty12"];
                this.columnqty13 = base.Columns["qty13"];
                this.columnqty14 = base.Columns["qty14"];
                this.columnqty15 = base.Columns["qty15"];
                this.columnqty16 = base.Columns["qty16"];
                this.columnqty17 = base.Columns["qty17"];
                this.columnqty18 = base.Columns["qty18"];
                this.columnqty19 = base.Columns["qty19"];
                this.columnqty20 = base.Columns["qty20"];
                this.columnqty21 = base.Columns["qty21"];
                this.columnqty22 = base.Columns["qty22"];
                this.columnbranch = base.Columns["branch"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnproduct_dep = new global::System.Data.DataColumn("product_dep", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnproduct_dep);
                this.columnproduct = new global::System.Data.DataColumn("product", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnproduct);
                this.columndate = new global::System.Data.DataColumn("date", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndate);
                this.columntime = new global::System.Data.DataColumn("time", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntime);
                this.columnto_date = new global::System.Data.DataColumn("to_date", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnto_date);
                this.columnfrom_date = new global::System.Data.DataColumn("from_date", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfrom_date);
                this.columnbatch_no = new global::System.Data.DataColumn("batch_no", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbatch_no);
                this.columnitem = new global::System.Data.DataColumn("item", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnitem);
                this.columnqty = new global::System.Data.DataColumn("qty", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnqty);
                this.columnstatus = new global::System.Data.DataColumn("status", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnstatus);
                this.columnqty1 = new global::System.Data.DataColumn("qty1", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnqty1);
                this.columnqty2 = new global::System.Data.DataColumn("qty2", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnqty2);
                this.columnqty3 = new global::System.Data.DataColumn("qty3", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnqty3);
                this.columnqty4 = new global::System.Data.DataColumn("qty4", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnqty4);
                this.columnqty5 = new global::System.Data.DataColumn("qty5", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnqty5);
                this.columnqty6 = new global::System.Data.DataColumn("qty6", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnqty6);
                this.columnqty7 = new global::System.Data.DataColumn("qty7", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnqty7);
                this.columnqty8 = new global::System.Data.DataColumn("qty8", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnqty8);
                this.columnqty9 = new global::System.Data.DataColumn("qty9", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnqty9);
                this.columnqty10 = new global::System.Data.DataColumn("qty10", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnqty10);
                this.columnqty11 = new global::System.Data.DataColumn("qty11", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnqty11);
                this.columnqty12 = new global::System.Data.DataColumn("qty12", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnqty12);
                this.columnqty13 = new global::System.Data.DataColumn("qty13", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnqty13);
                this.columnqty14 = new global::System.Data.DataColumn("qty14", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnqty14);
                this.columnqty15 = new global::System.Data.DataColumn("qty15", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnqty15);
                this.columnqty16 = new global::System.Data.DataColumn("qty16", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnqty16);
                this.columnqty17 = new global::System.Data.DataColumn("qty17", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnqty17);
                this.columnqty18 = new global::System.Data.DataColumn("qty18", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnqty18);
                this.columnqty19 = new global::System.Data.DataColumn("qty19", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnqty19);
                this.columnqty20 = new global::System.Data.DataColumn("qty20", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnqty20);
                this.columnqty21 = new global::System.Data.DataColumn("qty21", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnqty21);
                this.columnqty22 = new global::System.Data.DataColumn("qty22", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnqty22);
                this.columnbranch = new global::System.Data.DataColumn("branch", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbranch);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Production_tableRow NewProduction_tableRow() {
                return ((Production_tableRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new Production_tableRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(Production_tableRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.Production_tableRowChanged != null)) {
                    this.Production_tableRowChanged(this, new Production_tableRowChangeEvent(((Production_tableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.Production_tableRowChanging != null)) {
                    this.Production_tableRowChanging(this, new Production_tableRowChangeEvent(((Production_tableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.Production_tableRowDeleted != null)) {
                    this.Production_tableRowDeleted(this, new Production_tableRowChangeEvent(((Production_tableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.Production_tableRowDeleting != null)) {
                    this.Production_tableRowDeleting(this, new Production_tableRowChangeEvent(((Production_tableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveProduction_tableRow(Production_tableRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                Production ds = new Production();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "Production_tableDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class Production_tableRow : global::System.Data.DataRow {
            
            private Production_tableDataTable tableProduction_table;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal Production_tableRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableProduction_table = ((Production_tableDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string product_dep {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.product_depColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'product_dep\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.product_depColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string product {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.productColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'product\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.productColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string date {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.dateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'date\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.dateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string time {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.timeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'time\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.timeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string to_date {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.to_dateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'to_date\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.to_dateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string from_date {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.from_dateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'from_date\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.from_dateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string batch_no {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.batch_noColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'batch_no\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.batch_noColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string item {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.itemColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'item\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.itemColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string qty {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.qtyColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'qty\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.qtyColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string status {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.statusColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'status\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.statusColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string qty1 {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.qty1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'qty1\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.qty1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string qty2 {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.qty2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'qty2\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.qty2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string qty3 {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.qty3Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'qty3\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.qty3Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string qty4 {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.qty4Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'qty4\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.qty4Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string qty5 {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.qty5Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'qty5\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.qty5Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string qty6 {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.qty6Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'qty6\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.qty6Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string qty7 {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.qty7Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'qty7\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.qty7Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string qty8 {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.qty8Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'qty8\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.qty8Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string qty9 {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.qty9Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'qty9\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.qty9Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string qty10 {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.qty10Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'qty10\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.qty10Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string qty11 {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.qty11Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'qty11\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.qty11Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string qty12 {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.qty12Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'qty12\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.qty12Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string qty13 {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.qty13Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'qty13\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.qty13Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string qty14 {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.qty14Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'qty14\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.qty14Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string qty15 {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.qty15Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'qty15\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.qty15Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string qty16 {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.qty16Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'qty16\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.qty16Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string qty17 {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.qty17Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'qty17\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.qty17Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string qty18 {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.qty18Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'qty18\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.qty18Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string qty19 {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.qty19Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'qty19\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.qty19Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string qty20 {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.qty20Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'qty20\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.qty20Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string qty21 {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.qty21Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'qty21\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.qty21Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string qty22 {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.qty22Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'qty22\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.qty22Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string branch {
                get {
                    try {
                        return ((string)(this[this.tableProduction_table.branchColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'branch\' in table \'Production_table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableProduction_table.branchColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isproduct_depNull() {
                return this.IsNull(this.tableProduction_table.product_depColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setproduct_depNull() {
                this[this.tableProduction_table.product_depColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsproductNull() {
                return this.IsNull(this.tableProduction_table.productColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetproductNull() {
                this[this.tableProduction_table.productColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsdateNull() {
                return this.IsNull(this.tableProduction_table.dateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetdateNull() {
                this[this.tableProduction_table.dateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IstimeNull() {
                return this.IsNull(this.tableProduction_table.timeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SettimeNull() {
                this[this.tableProduction_table.timeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isto_dateNull() {
                return this.IsNull(this.tableProduction_table.to_dateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setto_dateNull() {
                this[this.tableProduction_table.to_dateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isfrom_dateNull() {
                return this.IsNull(this.tableProduction_table.from_dateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setfrom_dateNull() {
                this[this.tableProduction_table.from_dateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isbatch_noNull() {
                return this.IsNull(this.tableProduction_table.batch_noColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setbatch_noNull() {
                this[this.tableProduction_table.batch_noColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsitemNull() {
                return this.IsNull(this.tableProduction_table.itemColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetitemNull() {
                this[this.tableProduction_table.itemColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsqtyNull() {
                return this.IsNull(this.tableProduction_table.qtyColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetqtyNull() {
                this[this.tableProduction_table.qtyColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsstatusNull() {
                return this.IsNull(this.tableProduction_table.statusColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetstatusNull() {
                this[this.tableProduction_table.statusColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isqty1Null() {
                return this.IsNull(this.tableProduction_table.qty1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setqty1Null() {
                this[this.tableProduction_table.qty1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isqty2Null() {
                return this.IsNull(this.tableProduction_table.qty2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setqty2Null() {
                this[this.tableProduction_table.qty2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isqty3Null() {
                return this.IsNull(this.tableProduction_table.qty3Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setqty3Null() {
                this[this.tableProduction_table.qty3Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isqty4Null() {
                return this.IsNull(this.tableProduction_table.qty4Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setqty4Null() {
                this[this.tableProduction_table.qty4Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isqty5Null() {
                return this.IsNull(this.tableProduction_table.qty5Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setqty5Null() {
                this[this.tableProduction_table.qty5Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isqty6Null() {
                return this.IsNull(this.tableProduction_table.qty6Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setqty6Null() {
                this[this.tableProduction_table.qty6Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isqty7Null() {
                return this.IsNull(this.tableProduction_table.qty7Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setqty7Null() {
                this[this.tableProduction_table.qty7Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isqty8Null() {
                return this.IsNull(this.tableProduction_table.qty8Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setqty8Null() {
                this[this.tableProduction_table.qty8Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isqty9Null() {
                return this.IsNull(this.tableProduction_table.qty9Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setqty9Null() {
                this[this.tableProduction_table.qty9Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isqty10Null() {
                return this.IsNull(this.tableProduction_table.qty10Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setqty10Null() {
                this[this.tableProduction_table.qty10Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isqty11Null() {
                return this.IsNull(this.tableProduction_table.qty11Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setqty11Null() {
                this[this.tableProduction_table.qty11Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isqty12Null() {
                return this.IsNull(this.tableProduction_table.qty12Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setqty12Null() {
                this[this.tableProduction_table.qty12Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isqty13Null() {
                return this.IsNull(this.tableProduction_table.qty13Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setqty13Null() {
                this[this.tableProduction_table.qty13Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isqty14Null() {
                return this.IsNull(this.tableProduction_table.qty14Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setqty14Null() {
                this[this.tableProduction_table.qty14Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isqty15Null() {
                return this.IsNull(this.tableProduction_table.qty15Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setqty15Null() {
                this[this.tableProduction_table.qty15Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isqty16Null() {
                return this.IsNull(this.tableProduction_table.qty16Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setqty16Null() {
                this[this.tableProduction_table.qty16Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isqty17Null() {
                return this.IsNull(this.tableProduction_table.qty17Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setqty17Null() {
                this[this.tableProduction_table.qty17Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isqty18Null() {
                return this.IsNull(this.tableProduction_table.qty18Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setqty18Null() {
                this[this.tableProduction_table.qty18Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isqty19Null() {
                return this.IsNull(this.tableProduction_table.qty19Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setqty19Null() {
                this[this.tableProduction_table.qty19Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isqty20Null() {
                return this.IsNull(this.tableProduction_table.qty20Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setqty20Null() {
                this[this.tableProduction_table.qty20Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isqty21Null() {
                return this.IsNull(this.tableProduction_table.qty21Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setqty21Null() {
                this[this.tableProduction_table.qty21Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isqty22Null() {
                return this.IsNull(this.tableProduction_table.qty22Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setqty22Null() {
                this[this.tableProduction_table.qty22Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsbranchNull() {
                return this.IsNull(this.tableProduction_table.branchColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetbranchNull() {
                this[this.tableProduction_table.branchColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class Production_tableRowChangeEvent : global::System.EventArgs {
            
            private Production_tableRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Production_tableRowChangeEvent(Production_tableRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Production_tableRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591